---
dist: bionic
addons:
  apt:
    packages:
      - docker-ce
      - libssl-dev
      - libffi-dev
      - python3
      - python3-pip
      - python3-setuptools
      - python3-software-properties
      - python3-wheel

language: minimal

services:
  - docker

env:
  global:
    - ROLE_NAME: ansible-common
    - AUTHOR_NAME: coglinev3
    - MOLECULE_DISTRO: coglinev3/ansible
  matrix:
    - MOLECULE_DISTRO_VERSION: alpine-3.9
    - MOLECULE_DISTRO_VERSION: alpine-3.10
    - MOLECULE_DISTRO_VERSION: alpine-3.11
    - MOLECULE_DISTRO_VERSION: alpine-3.12
    - MOLECULE_DISTRO_VERSION: centos-7
    - MOLECULE_DISTRO_VERSION: centos-8
    - MOLECULE_DISTRO_VERSION: debian-8
    - MOLECULE_DISTRO_VERSION: debian-9
    - MOLECULE_DISTRO_VERSION: debian-10
    - MOLECULE_DISTRO_VERSION: fedora-32
    - MOLECULE_DISTRO_VERSION: fedora-33
    - MOLECULE_DISTRO_VERSION: ubuntu-16.04
    - MOLECULE_DISTRO_VERSION: ubuntu-18.04
    - MOLECULE_DISTRO_VERSION: ubuntu-20.04

install:
  # Install test dependencies.
  - pip3 install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ${ROLE_NAME} ${AUTHOR_NAME}.${ROLE_NAME}
  - cd ${AUTHOR_NAME}.${ROLE_NAME}

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
