---
# file: roles/ansible-common/tasks/setup-Debian.yml

- name: "Debian: Install essential packages for some Ansible modules"
  apt:
    name: "{{ essential_packages }}"
    state: "{{ essential_packages_state }}"
  when: not ansible_check_mode
  tags:
    - install

- name: "Debian: Install common packages for every Linux distribution"
  apt:
    name: "{{ common_packages }}"
    state: "{{ common_packages_state }}"
  when: not ansible_check_mode
  tags:
    - install
