---
# file: roles/ansible-common/tasks/setup-RedHat.yml

- name: "RedHat: Upgrade all packages to the latest version"
  yum:
    name: "*"
    state: latest
    update_cache: "{{ common_packages_update_cache | default('false') }}"
  when: common_packages_update_all

# The EPEL Repository should be installed on all EL Systems
- name: "RedHat: Install EPEL Repository"
  yum:
    name: epel-release
    state: present
    update_cache: "yes"
  when: not ansible_distribution == "Fedora"
  tags:
    - install

- name: "RedHat: Install essential packages for some Ansible modules"
  yum:
    name: "{{ essential_packages }}"
    state: "{{ essential_packages_state }}"
    update_cache: "yes"
  when: not ansible_check_mode
  tags:
    - install

- name: "RedHat: Install common packages for every Linux distribution"
  yum:
    name: "{{ common_packages }}"
    state: "{{ common_packages_state }}"
  when: not ansible_check_mode
  tags:
    - install
