---
# file: roles/ansible-common/tasks/setup-RedHat.yml

# The EPEL Repository should be installed on all EL Systems
- name: "RedHat: Install EPEL Repository"
  yum:
    name: epel-release
    state: present
    update_cache: "yes"
  tags:
    - install

- name: "RedHat: Install essential packages for some Ansible modules"
  yum:
    name: "{{ essential_packages }}"
    state: "{{ essential_packages_state }}"
    update_cache: "yes"
  when: not ansible_check_mode
  tags:
    - install

- name: "RedHat: Install common packages for every Linux distribution"
  yum:
    name: "{{ common_packages }}"
    state: "{{ common_packages_state }}"
  when: not ansible_check_mode
  tags:
    - install
