---
- name: Converge
  hosts: all
  tasks:
    - name: "Include coglinev3.ansible-common"
      include_role:
        name: "coglinev3.ansible-common"

    - name: "Log in as User ansible and execute git --version"
      remote_user: root
      become: true
      become_user: ansible
      shell: PATH=/usr/local/bin:/bin:/usr/bin git --version
      register: git_version

    - name: Check if git is installed correctly.
      assert:
        that:
          - git_version.rc == 0
        fail_msg: "Git not installed properly"
        success_msg: "Git installed correctly"
