---
- name: Converge
  hosts: all
  tasks:
    - name: "Include coglinev3.ansible-common"
      include_role:
        name: "coglinev3.ansible-common"

    - name: "Log in as User ansible and execute git --version"
      become: true
      #become_user: ansible
      become_user: ansible
      command: git --version
      environment:
        PATH: /usr/local/bin:/bin:/usr/bin
      changed_when: false
      args:
        warn: false # set warn=false to prevent warning
      register: git_version

    - name: Check if git is installed correctly.
      assert:
        that:
          - git_version.rc == 0
        fail_msg: "Git not installed properly"
        success_msg: "Role works fine, {{ git_version.stdout }} installed correctly"
